import { useId, useState, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes } from 'react';
import { cn, formatMoney } from '../../lib/utils';
import { useUi } from '../../app/providers';

export function MaterialIcon({ name, size = 24, label, className }: { name: string; size?: number; label?: string; className?: string }) { return <span className={cn('material-symbols-rounded shrink-0', className)} style={{ fontSize: size }} aria-hidden={label ? undefined : true} aria-label={label}>{name}</span>; }
export function Button({ variant = 'filled', loading, icon, className, children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'filled'|'tonal'|'outlined'|'text'|'danger'; loading?: boolean; icon?: string }) { const styles={filled:'bg-primary text-on-primary hover:bg-primary-hover',tonal:'bg-primary-container text-primary hover:brightness-95',outlined:'border border-border text-primary hover:bg-primary-container',text:'text-primary hover:bg-primary-container',danger:'bg-error text-white hover:brightness-90'}; return <button className={cn('interactive inline-flex min-h-10 items-center justify-center gap-2 rounded-xl px-4 py-2 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-50',styles[variant],className)} disabled={loading || props.disabled} {...props}>{loading ? <MaterialIcon name="progress_activity" className="animate-spin" /> : icon ? <MaterialIcon name={icon} size={20} /> : null}{children}</button>; }
export function IconButton({ label, icon, className, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { label: string; icon: string }) { return <button aria-label={label} title={label} className={cn('interactive inline-grid size-11 place-items-center rounded-full text-text-secondary hover:bg-surface-container hover:text-text-primary',className)} {...props}><MaterialIcon name={icon} /></button>; }
export function TextField({ label, error, hint, className, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string; error?: string; hint?: string }) { const id=useId(); return <label className={cn('grid gap-1.5 text-sm font-medium',className)} htmlFor={id}>{label}<input id={id} className={cn('min-h-12 rounded-xl border bg-surface px-4 text-text-primary placeholder:text-text-secondary/70',error?'border-error':'border-border','focus:border-primary')} aria-invalid={!!error} aria-describedby={error||hint?`${id}-help`:undefined} {...props}/>{(error||hint)&&<span id={`${id}-help`} className={cn('text-xs font-normal',error?'text-error':'text-text-secondary')}>{error||hint}</span>}</label>; }
export function PasswordField(props: Omit<Parameters<typeof TextField>[0], 'type'>) { const [visible,setVisible]=useState(false); return <div className="relative"><TextField {...props} type={visible?'text':'password'} className="[&_input]:pr-12"/><button type="button" onClick={()=>setVisible(!visible)} className="absolute right-2 top-7 grid size-10 place-items-center rounded-full" aria-label={visible?'Ocultar contraseña':'Mostrar contraseña'}><MaterialIcon name={visible?'visibility_off':'visibility'} size={20}/></button></div>; }
export function Select({ label, options, error, ...props }: SelectHTMLAttributes<HTMLSelectElement> & { label: string; options: {value:string;label:string}[]; error?:string }) { const id=useId(); return <label htmlFor={id} className="grid gap-1.5 text-sm font-medium">{label}<select id={id} className={cn('min-h-12 rounded-xl border bg-surface px-4',error?'border-error':'border-border')} aria-invalid={!!error} {...props}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>{error&&<span className="text-xs font-normal text-error">{error}</span>}</label>; }
export function SearchField(props: InputHTMLAttributes<HTMLInputElement>) { return <div className="relative"><MaterialIcon name="search" size={20} className="absolute left-3 top-3 text-text-secondary"/><input aria-label="Buscar" className="min-h-11 w-full rounded-full border border-border bg-surface-container pl-10 pr-4" placeholder="Buscar…" type="search" {...props}/></div>; }
export function Checkbox({ label, ...props }: InputHTMLAttributes<HTMLInputElement> & {label:string}) { return <label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" className="size-5 accent-primary" {...props}/>{label}</label>; }
export function Radio({ label, ...props }: InputHTMLAttributes<HTMLInputElement> & {label:string}) { return <label className="flex min-h-11 items-center gap-3 text-sm"><input type="radio" className="size-5 accent-primary" {...props}/>{label}</label>; }
export function Switch({ label, checked, onChange }: {label:string;checked:boolean;onChange:(checked:boolean)=>void}) { return <label className="flex min-h-11 cursor-pointer items-center justify-between gap-4"><span className="text-sm font-medium">{label}</span><input type="checkbox" role="switch" className="peer sr-only" checked={checked} onChange={e=>onChange(e.target.checked)}/><span className="relative h-7 w-12 rounded-full bg-border peer-checked:bg-primary after:absolute after:left-1 after:top-1 after:size-5 after:rounded-full after:bg-white after:transition-transform peer-checked:after:translate-x-5"/></label>; }
export function SegmentedControl<T extends string>({ value, options, onChange }: {value:T;options:{value:T;label:string}[];onChange:(value:T)=>void}) { return <div className="flex rounded-xl bg-surface-container p-1" role="radiogroup">{options.map(o=><button type="button" role="radio" aria-checked={value===o.value} key={o.value} onClick={()=>onChange(o.value)} className={cn('min-h-10 flex-1 rounded-lg px-3 text-sm font-semibold',value===o.value?'bg-surface text-primary shadow-sm':'text-text-secondary')}>{o.label}</button>)}</div>; }
export function Chip({ children, selected=false, onRemove }: {children:ReactNode;selected?:boolean;onRemove?:()=>void}) { return <span className={cn('inline-flex min-h-8 items-center gap-1 rounded-lg border px-3 text-xs font-semibold',selected?'border-primary bg-primary-container text-primary':'border-border bg-surface')}>{children}{onRemove&&<button aria-label="Quitar filtro" onClick={onRemove}><MaterialIcon name="close" size={16}/></button>}</span>; }
export function Badge({ children, tone='neutral' }: {children:ReactNode;tone?:'neutral'|'success'|'warning'|'error'|'info'}) { const styles={neutral:'bg-surface-container text-text-secondary',success:'bg-success-container text-success',warning:'bg-warning-container text-warning',error:'bg-error-container text-error',info:'bg-info-container text-info'}; return <span className={cn('inline-flex rounded-full px-2.5 py-1 text-xs font-semibold',styles[tone])}>{children}</span>; }
export function Card({ children, className }: {children:ReactNode;className?:string}) { return <section className={cn('card p-5 desktop:p-6',className)}>{children}</section>; }
export function MetricCard({ label, value, icon, tone='primary', context }: {label:string;value:number;icon:string;tone?:'primary'|'success'|'warning'|'error';context:string}) { return <Card><div className="flex items-start justify-between"><div><p className="text-sm text-text-secondary">{label}</p><FinancialAmount value={value} compact className="mt-2 text-2xl font-semibold"/><p className="mt-2 text-xs text-text-secondary">{context}</p></div><span className={cn('grid size-10 place-items-center rounded-xl',`bg-${tone}-container text-${tone}`)}><MaterialIcon name={icon}/></span></div></Card>; }
export function FinancialAmount({ value, compact=false, className, prefix='' }: {value:number;compact?:boolean;className?:string;prefix?:string}) { const {amountsHidden}=useUi(); return <span className={cn('amount',className)}>{prefix}{formatMoney(value,amountsHidden,compact)}</span>; }
export function ProgressBar({ value, label }: {value:number;label?:string}) { const clamped=Math.min(value,100); return <div><div className="h-2 overflow-hidden rounded-full bg-surface-high" role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100} aria-label={label}><div className={cn('h-full rounded-full',value>=100?'bg-error':value>=80?'bg-warning':'bg-primary')} style={{width:`${clamped}%`}}/></div>{label&&<p className="sr-only">{label}: {value.toFixed(0)} %</p>}</div>; }
export function Skeleton({ className }: {className?:string}) { return <span aria-hidden="true" className={cn('block animate-pulse rounded-lg bg-surface-high',className)}/>; }
export function EmptyState({ title, description, action }: {title:string;description:string;action?:ReactNode}) { return <div className="grid min-h-64 place-items-center text-center"><div className="max-w-md"><MaterialIcon name="inbox" size={48} className="text-text-secondary"/><h2 className="mt-4 text-xl font-semibold">{title}</h2><p className="mt-2 text-sm text-text-secondary">{description}</p>{action&&<div className="mt-5">{action}</div>}</div></div>; }
export function ErrorState({ onRetry }: {onRetry?:()=>void}) { return <div role="alert" className="rounded-2xl border border-error bg-error-container p-5"><h2 className="font-semibold text-error">No pudimos cargar esta sección</h2><p className="mt-1 text-sm">Tu información sigue segura. Intenta nuevamente.</p>{onRetry&&<Button variant="outlined" className="mt-4" onClick={onRetry}>Reintentar</Button>}</div>; }
export function Modal({ open, title, children, onClose }: {open:boolean;title:string;children:ReactNode;onClose:()=>void}) { if(!open)return null; return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-6" role="presentation" onMouseDown={onClose}><div role="dialog" aria-modal="true" aria-labelledby="modal-title" className="card w-full max-w-lg rounded-3xl p-6 shadow-[var(--shadow-3)]" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 id="modal-title" className="text-xl font-semibold">{title}</h2><IconButton label="Cerrar" icon="close" onClick={onClose}/></div><div className="mt-4">{children}</div></div></div>; }
export function Drawer({ open, children, onClose }: {open:boolean;children:ReactNode;onClose:()=>void}) { return <><button aria-label="Cerrar navegación" onClick={onClose} className={cn('fixed inset-0 z-30 bg-black/40 laptop:hidden',open?'block':'hidden')}/><aside className={cn('fixed inset-y-0 left-0 z-40 w-72 bg-surface transition-transform laptop:hidden',open?'translate-x-0':'-translate-x-full')}>{children}</aside></>; }
export function Snackbar({ message, open }: {message:string;open:boolean}) { return <div role="status" aria-live="polite" className={cn('fixed bottom-6 left-1/2 z-[60] -translate-x-1/2 rounded-xl bg-text-primary px-5 py-3 text-sm text-bg shadow-lg transition',open?'opacity-100':'pointer-events-none opacity-0')}>{message}</div>; }
export function Tooltip({ label, children }: {label:string;children:ReactNode}) { return <span title={label}>{children}</span>; }
export function DropdownMenu({ label, items }: {label:string;items:string[]}) { return <details className="relative"><summary className="list-none"><IconButton label={label} icon="more_vert"/></summary><div className="absolute right-0 z-20 min-w-44 rounded-xl border border-border bg-surface p-1 shadow-[var(--shadow-2)]">{items.map(i=><button key={i} className="block min-h-10 w-full rounded-lg px-3 text-left text-sm hover:bg-surface-container">{i}</button>)}</div></details>; }
export function DateRangeSelector() { return <Button variant="outlined" icon="date_range">Este mes</Button>; }
export function Pagination({ page=1,total=3 }: {page?:number;total?:number}) { return <nav aria-label="Paginación" className="flex items-center justify-end gap-2"><IconButton label="Página anterior" icon="chevron_left" disabled={page===1}/><span className="text-sm">Página {page} de {total}</span><IconButton label="Página siguiente" icon="chevron_right" disabled={page===total}/></nav>; }
export function ThemeToggle() { const {theme,setTheme}=useUi(); return <label className="grid gap-1 text-xs text-text-secondary"><span>Tema</span><select aria-label="Tema de la interfaz" value={theme} onChange={e=>setTheme(e.target.value as 'light'|'dark'|'system')} className="min-h-10 rounded-xl border border-border bg-surface px-3 text-sm text-text-primary"><option value="system">Sistema</option><option value="light">Claro</option><option value="dark">Oscuro</option></select></label>; }
export function PrivacyAmountToggle() { const {amountsHidden,toggleAmounts}=useUi(); return <IconButton label={amountsHidden?'Mostrar importes':'Ocultar importes'} icon={amountsHidden?'visibility':'visibility_off'} onClick={toggleAmounts}/>; }
