import { useMemo, useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate } from 'react-router-dom';
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip as ChartTooltip } from 'recharts';
import { Button, Card, Chip, DateRangeSelector, EmptyState, ErrorState, FinancialAmount, MaterialIcon, MetricCard, ProgressBar, SearchField, SegmentedControl, Select, Switch, ThemeToggle, TextField } from '../components/ui';
import { DataTable } from '../components/finance/TransactionTable';
import { PageHeader } from '../components/layout/AppShell';
import { useAuth } from '../app/auth';
import { accountsService, budgetsService, categoriesService, transactionsService } from '../services/financeService';
import type { AccountType } from '../services/types';
import { formatMoney, formatPercent } from '../lib/utils';

const keys={accounts:['accounts'] as const,categories:['categories'] as const,transactions:['transactions'] as const,budgets:['budgets'] as const};
const useFinance=()=>({accounts:useQuery({queryKey:keys.accounts,queryFn:accountsService.list}),categories:useQuery({queryKey:keys.categories,queryFn:categoriesService.list}),transactions:useQuery({queryKey:keys.transactions,queryFn:transactionsService.list}),budgets:useQuery({queryKey:keys.budgets,queryFn:budgetsService.list})});
const maps=<T extends {id:string;name:string}>(items:T[]=[]):Record<string,string>=>Object.fromEntries(items.map(x=>[x.id,x.name]));

export function DashboardPage(){const {user}=useAuth(),q=useFinance();if([q.accounts,q.transactions,q.budgets].some(x=>x.isLoading))return <Card>Cargando resumen financiero…</Card>;if([q.accounts,q.transactions,q.budgets].some(x=>x.isError))return <ErrorState onRetry={()=>void Promise.all([q.accounts.refetch(),q.transactions.refetch(),q.budgets.refetch()])}/>;const accounts=q.accounts.data??[],tx=q.transactions.data??[],budgets=q.budgets.data??[],done=tx.filter(t=>t.status==='Completed'),income=done.filter(t=>t.type==='Income').reduce((s,t)=>s+t.amount,0),expense=done.filter(t=>t.type==='Expense').reduce((s,t)=>s+t.amount,0),balance=accounts.filter(a=>a.isActive).reduce((s,a)=>s+a.currentBalance,0);return <><PageHeader title={`Hola, ${user?.displayName.split(' ')[0]??'usuario'}`} description={`Resumen financiero · ${user?.baseCurrency??'DOP'}`} action={<Link to="/app/transactions/new"><Button icon="add">Registrar movimiento</Button></Link>}/><section className="grid gap-4 tablet:grid-cols-2 desktop:grid-cols-4"><MetricCard label="Balance total" value={balance} icon="account_balance_wallet" context="Cuentas activas"/><MetricCard label="Ingresos" value={income} icon="south_west" tone="success" context="Movimientos completados"/><MetricCard label="Gastos" value={expense} icon="north_east" tone="error" context="Sin transferencias"/><MetricCard label="Ahorro neto" value={income-expense} icon="savings" context="Ingresos menos gastos"/></section><div className="mt-6 grid gap-6 desktop:grid-cols-2"><Card><div className="flex justify-between"><h2 className="text-lg font-semibold">Presupuestos</h2><Link className="text-sm font-semibold text-primary" to="/app/budgets">Ver todos</Link></div><div className="mt-5 grid gap-4">{budgets.slice(0,3).map(b=><div key={b.id}><div className="mb-2 flex justify-between text-sm"><span>{b.name}</span><span>{formatPercent(b.percentageUsed)}</span></div><ProgressBar value={b.percentageUsed}/></div>)}{!budgets.length&&<p className="text-sm text-text-secondary">Aún no tienes presupuestos.</p>}</div></Card><Card><h2 className="mb-4 text-lg font-semibold">Movimientos recientes</h2>{tx.length?<DataTable rows={tx.slice(0,5)} accounts={maps(accounts)} categories={maps(q.categories.data)}/>:<EmptyState title="Sin movimientos" description="Registra tu primera transacción."/>}</Card></div></>}

export function TransactionsPage(){const [search,setSearch]=useState(''),q=useFinance();if(q.transactions.isLoading)return <Card>Cargando transacciones…</Card>;if(q.transactions.isError)return <ErrorState onRetry={()=>void q.transactions.refetch()}/>;const rows=(q.transactions.data??[]).filter(t=>t.description.toLowerCase().includes(search.toLowerCase()));return <><PageHeader title="Transacciones" description="Ingresos, gastos y transferencias sincronizados con la API." action={<Link to="/app/transactions/new"><Button icon="add">Nueva transacción</Button></Link>}/><Card className="mb-5"><div className="grid gap-3 tablet:grid-cols-[1fr_auto]"><SearchField value={search} onChange={e=>setSearch(e.target.value)}/><Button variant="outlined" icon="download" disabled>Exportar CSV</Button></div></Card>{rows.length?<DataTable rows={rows} accounts={maps(q.accounts.data)} categories={maps(q.categories.data)}/>:<Card><EmptyState title="No hay transacciones" description="Registra un movimiento o cambia la búsqueda."/></Card>}</>}

export function NewTransactionPage(){const [type,setType]=useState<'Expense'|'Income'|'Transfer'>('Expense'),nav=useNavigate(),client=useQueryClient(),q=useFinance();const mutation=useMutation({mutationFn:async(form:HTMLFormElement)=>{const f=new FormData(form),amount=Number(f.get('amount')),transactionDate=new Date(String(f.get('date'))).toISOString(),description=String(f.get('description'));if(type==='Transfer')return transactionsService.transfer({amount,currencyCode:'DOP',transactionDate,sourceAccountId:String(f.get('accountId')),destinationAccountId:String(f.get('destinationAccountId')),description});return transactionsService.create({type,amount,currencyCode:'DOP',transactionDate,accountId:String(f.get('accountId')),categoryId:String(f.get('categoryId')||'')||undefined,description})},onSuccess:async()=>{await Promise.all([client.invalidateQueries({queryKey:keys.transactions}),client.invalidateQueries({queryKey:keys.accounts})]);nav('/app/transactions')}});const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();mutation.mutate(e.currentTarget)},accountOptions=(q.accounts.data??[]).map(a=>({value:a.id,label:a.name})),categoryOptions=(q.categories.data??[]).filter(c=>c.type===type).map(c=>({value:c.id,label:c.name}));return <><PageHeader title="Nueva transacción" description="El movimiento se guardará mediante la API."/><form className="mx-auto max-w-3xl" onSubmit={submit}><Card><SegmentedControl value={type} onChange={setType} options={[{value:'Expense',label:'Gasto'},{value:'Income',label:'Ingreso'},{value:'Transfer',label:'Transferencia'}]}/><div className="mt-6 grid gap-5 tablet:grid-cols-2"><TextField name="amount" label="Importe" type="number" min="0.01" step="0.01" required/><Select name="accountId" label={type==='Transfer'?'Cuenta de origen':'Cuenta'} options={accountOptions} required/>{type==='Transfer'?<Select name="destinationAccountId" label="Cuenta de destino" options={accountOptions} required/>:<Select name="categoryId" label="Categoría" options={[{value:'',label:'Sin categoría'},...categoryOptions]}/>}<TextField name="date" label="Fecha" type="datetime-local" required/><TextField name="description" label="Descripción" required className="tablet:col-span-2"/></div>{mutation.isError&&<p role="alert" className="mt-4 text-sm text-error">No se pudo guardar. Revisa los datos.</p>}<div className="mt-6 flex justify-end gap-3"><Link to="/app/transactions"><Button type="button" variant="text">Cancelar</Button></Link><Button type="submit" loading={mutation.isPending}>Guardar</Button></div></Card></form></>}

export function AccountsPage(){const q=useQuery({queryKey:keys.accounts,queryFn:accountsService.list});return <><PageHeader title="Cuentas" description="Saldos calculados por el backend." action={<Link to="/app/accounts/new"><Button icon="add">Nueva cuenta</Button></Link>}/>{q.isLoading?<Card>Cargando cuentas…</Card>:q.isError?<ErrorState onRetry={()=>void q.refetch()}/>:q.data?.length?<div className="grid gap-4 tablet:grid-cols-2 desktop:grid-cols-3">{q.data.map(a=><Card key={a.id}><span className="grid size-11 place-items-center rounded-xl bg-primary-container text-primary"><MaterialIcon name={a.type==='CreditCard'?'credit_card':a.type==='Cash'?'payments':'account_balance'}/></span><h2 className="mt-5 font-semibold">{a.name}</h2><p className="text-sm text-text-secondary">{a.type} · {a.currencyCode}</p><FinancialAmount value={a.currentBalance} className="mt-4 block text-2xl font-semibold"/></Card>)}</div>:<Card><EmptyState title="Sin cuentas" description="Crea una cuenta para comenzar."/></Card>}</>}

export function NewAccountPage(){const nav=useNavigate(),client=useQueryClient(),mutation=useMutation({mutationFn:(form:HTMLFormElement)=>{const f=new FormData(form);return accountsService.create({name:String(f.get('name')),type:String(f.get('type')) as AccountType,currencyCode:'DOP',initialBalance:Number(f.get('initialBalance')),initialBalanceDate:String(f.get('date')),description:String(f.get('description')||'')||undefined})},onSuccess:async()=>{await client.invalidateQueries({queryKey:keys.accounts});nav('/app/accounts')}});return <><PageHeader title="Nueva cuenta" description="Nunca solicitamos credenciales bancarias."/><form className="mx-auto max-w-3xl" onSubmit={e=>{e.preventDefault();mutation.mutate(e.currentTarget)}}><Card><div className="grid gap-5 tablet:grid-cols-2"><Select name="type" label="Tipo" options={['Cash','BankAccount','Savings','CreditCard','DigitalWallet','PettyCash','Investment','Other'].map(value=>({value,label:value}))}/><TextField name="name" label="Nombre" required/><TextField name="initialBalance" label="Balance inicial" type="number" step="0.01" defaultValue="0" required/><TextField name="date" label="Fecha del balance" type="date" required/><TextField name="description" label="Descripción (opcional)" className="tablet:col-span-2"/></div>{mutation.isError&&<p className="mt-4 text-sm text-error">No se pudo crear la cuenta.</p>}<div className="mt-6 flex justify-end gap-3"><Link to="/app/accounts"><Button type="button" variant="text">Cancelar</Button></Link><Button loading={mutation.isPending}>Crear cuenta</Button></div></Card></form></>}

export function BudgetsPage(){const q=useQuery({queryKey:keys.budgets,queryFn:budgetsService.list}),items=q.data??[],total=items.reduce((s,b)=>s+b.amount,0),spent=items.reduce((s,b)=>s+b.amountSpent,0);return <><PageHeader title="Presupuestos" description="Seguimiento calculado desde las transacciones."/>{q.isError?<ErrorState onRetry={()=>void q.refetch()}/>:<><section className="grid gap-4 tablet:grid-cols-3"><MetricCard label="Presupuestado" value={total} icon="account_balance_wallet" context="Periodos configurados"/><MetricCard label="Consumido" value={spent} icon="payments" tone="warning" context={total?formatPercent(spent/total*100):'0 %'}/><MetricCard label="Disponible" value={total-spent} icon="savings" tone="success" context="Según movimientos"/></section><div className="mt-6 grid gap-4 tablet:grid-cols-2">{items.map(b=><Card key={b.id}><div className="flex justify-between"><h2 className="font-semibold">{b.name}</h2><span>{formatPercent(b.percentageUsed)}</span></div><p className="mt-2 text-sm text-text-secondary"><FinancialAmount value={b.amountSpent}/> de <FinancialAmount value={b.amount}/></p><div className="mt-4"><ProgressBar value={b.percentageUsed}/></div></Card>)}</div>{!q.isLoading&&!items.length&&<Card className="mt-6"><EmptyState title="Sin presupuestos" description="Podrás crearlos cuando existan categorías válidas."/></Card>}</>}</>}

export function ReportsPage(){const tx=useQuery({queryKey:keys.transactions,queryFn:transactionsService.list}),categories=useQuery({queryKey:keys.categories,queryFn:categoriesService.list});const data=useMemo(()=>{const names=maps(categories.data),sums=new Map<string,number>();(tx.data??[]).filter(t=>t.type==='Expense'&&t.status==='Completed').forEach(t=>{const name=t.categoryId?names[t.categoryId]??'Otros':'Otros';sums.set(name,(sums.get(name)??0)+t.amount)});return [...sums].map(([name,value],i)=>({name,value,color:['var(--color-primary)','var(--color-warning)','var(--color-info)','var(--color-success)'][i%4]}))},[tx.data,categories.data]);return <><PageHeader title="Reportes" description="Resumen calculado con datos de la API."/><div className="mb-5 flex gap-3"><DateRangeSelector/><Chip selected>DOP</Chip></div><Card><h2 className="text-lg font-semibold">Gastos por categoría</h2>{tx.isError?<ErrorState onRetry={()=>void tx.refetch()}/>:data.length?<div className="grid items-center tablet:grid-cols-2"><div className="h-72"><ResponsiveContainer><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={58} outerRadius={90}>{data.map(d=><Cell key={d.name} fill={d.color}/>)}</Pie><ChartTooltip formatter={v=>formatMoney(Number(v))}/></PieChart></ResponsiveContainer></div><ul className="grid gap-3">{data.map(d=><li key={d.name} className="flex justify-between"><span>{d.name}</span><strong>{formatMoney(d.value)}</strong></li>)}</ul></div>:<EmptyState title="Sin datos para reportar" description="Los gastos completados aparecerán aquí."/>}</Card></>}

export function SettingsPage(){const {user}=useAuth(),[notifications,setNotifications]=useState(true),[privateMode,setPrivateMode]=useState(false);return <><PageHeader title="Configuración" description="Perfil obtenido desde la API; la edición queda pendiente."/><div className="mx-auto grid max-w-4xl gap-6"><Card><h2 className="text-lg font-semibold">Perfil</h2><dl className="mt-4 grid gap-4 tablet:grid-cols-2"><div><dt className="text-sm text-text-secondary">Nombre</dt><dd>{user?.displayName}</dd></div><div><dt className="text-sm text-text-secondary">Correo</dt><dd>{user?.email}</dd></div><div><dt className="text-sm text-text-secondary">Idioma</dt><dd>{user?.preferredLanguage}</dd></div><div><dt className="text-sm text-text-secondary">Moneda</dt><dd>{user?.baseCurrency}</dd></div></dl></Card><Card><h2 className="text-lg font-semibold">Apariencia y privacidad local</h2><div className="mt-5 grid gap-5"><ThemeToggle/><Switch label="Ocultar importes al iniciar" checked={privateMode} onChange={setPrivateMode}/><Switch label="Notificaciones de presupuesto" checked={notifications} onChange={setNotifications}/></div></Card></div></>}
