import { zodResolver } from '@hookform/resolvers/zod';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useNavigate } from 'react-router-dom';
import { z } from 'zod';
import { Button, Card, Checkbox, MaterialIcon, PasswordField, TextField, ThemeToggle } from '../components/ui';
import { useAuth } from '../app/auth';
import { ApiError } from '../services/apiClient';

const emailSchema = z.object({ email: z.email('Escribe un correo válido') });
const loginSchema = emailSchema.extend({ password: z.string().min(12, 'Usa al menos 12 caracteres') });
const registerSchema = loginSchema.extend({ name: z.string().min(2, 'Escribe tu nombre'), accepted: z.literal(true, { error: 'Debes aceptar los términos' }) });
type LoginValues=z.infer<typeof loginSchema>; type RegisterValues=z.infer<typeof registerSchema>;

function AuthLayout({title,description,children}: {title:string;description:string;children:React.ReactNode}) { return <main className="min-h-screen bg-bg p-5"><div className="mx-auto flex max-w-6xl justify-end"><ThemeToggle/></div><div className="mx-auto grid min-h-[calc(100vh-90px)] max-w-6xl place-items-center laptop:grid-cols-2"><section className="hidden max-w-lg laptop:block"><span className="inline-grid size-12 place-items-center rounded-2xl bg-primary text-2xl font-bold text-on-primary">P</span><h1 className="mt-8 text-5xl font-medium leading-[1.15]">Tu dinero, con más claridad.</h1><p className="mt-5 text-lg text-text-secondary">Organiza tus finanzas personales sin juicios, con información precisa y acciones sencillas.</p></section><Card className="w-full max-w-md p-8"><Link to="/login" className="mb-7 inline-flex items-center gap-2 text-xl font-semibold text-primary"><span className="grid size-8 place-items-center rounded-xl bg-primary text-on-primary">P</span>PagaTo’</Link><h2 className="text-3xl font-medium">{title}</h2><p className="mb-7 mt-2 text-sm text-text-secondary">{description}</p>{children}</Card></div></main>; }

export function LoginPage() { const nav=useNavigate(); const auth=useAuth(); const [apiError,setApiError]=useState(''); const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<LoginValues>({resolver:zodResolver(loginSchema)}); return <AuthLayout title="Inicia sesión" description="Accede a tu espacio financiero."><form className="grid gap-5" onSubmit={handleSubmit(async values=>{setApiError('');try{await auth.login(values.email,values.password);nav('/app/dashboard');}catch(error){setApiError(error instanceof ApiError?error.message:'No pudimos iniciar sesión.');}})}><TextField label="Correo electrónico" type="email" autoComplete="email" error={errors.email?.message} {...register('email')}/><PasswordField label="Contraseña" autoComplete="current-password" error={errors.password?.message} {...register('password')}/>{apiError&&<p role="alert" className="rounded-xl bg-error-container p-3 text-sm text-error">{apiError}</p>}<div className="flex items-center justify-between"><Checkbox label="Recordarme"/><Link className="text-sm font-semibold text-primary" to="/forgot-password">¿Olvidaste tu contraseña?</Link></div><Button type="submit" loading={isSubmitting}>Iniciar sesión</Button><p className="text-center text-sm text-text-secondary">¿Aún no tienes cuenta? <Link className="font-semibold text-primary" to="/register">Crear cuenta</Link></p></form></AuthLayout>; }
export function RegisterPage() { const nav=useNavigate(); const auth=useAuth(); const [apiError,setApiError]=useState(''); const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<RegisterValues>({resolver:zodResolver(registerSchema)}); return <AuthLayout title="Crea tu cuenta" description="Comienza a organizar tus finanzas personales."><form className="grid gap-4" onSubmit={handleSubmit(async values=>{setApiError('');try{await auth.register(values.name,values.email,values.password);nav('/app/dashboard');}catch(error){setApiError(error instanceof ApiError?error.message:'No pudimos crear la cuenta.');}})}><TextField label="Nombre" autoComplete="name" error={errors.name?.message} {...register('name')}/><TextField label="Correo electrónico" type="email" autoComplete="email" error={errors.email?.message} {...register('email')}/><PasswordField label="Contraseña" autoComplete="new-password" hint="Mínimo 12 caracteres, con mayúscula, minúscula, número y símbolo" error={errors.password?.message} {...register('password')}/><div><Checkbox label="Acepto los términos" {...register('accepted')}/>{errors.accepted&&<p className="text-xs text-error">{errors.accepted.message}</p>}</div>{apiError&&<p role="alert" className="rounded-xl bg-error-container p-3 text-sm text-error">{apiError}</p>}<Button type="submit" loading={isSubmitting}>Crear cuenta</Button><Link className="text-center text-sm font-semibold text-primary" to="/login">Ya tengo una cuenta</Link></form></AuthLayout>; }
export function ForgotPasswordPage() { const [sent,setSent]=useState(false); const {register,handleSubmit,formState:{errors}}=useForm<{email:string}>({resolver:zodResolver(emailSchema)}); return <AuthLayout title="Recupera tu acceso" description="Te mostraremos cómo se vería el envío de instrucciones.">{sent?<SuccessBlock title="Revisa tu correo" text="Mostramos este estado como demostración; no se envió ningún mensaje." to="/reset-password" action="Continuar al restablecimiento"/>:<form className="grid gap-5" onSubmit={handleSubmit(()=>setSent(true))}><TextField label="Correo electrónico" type="email" error={errors.email?.message} {...register('email')}/><Button type="submit">Enviar instrucciones</Button><Link className="text-center text-sm text-primary" to="/login">Volver al inicio de sesión</Link></form>}</AuthLayout>; }
export function VerifyEmailPage() { return <AuthLayout title="Verifica tu correo" description="Este estado confirma el paso de seguridad sin contactar servicios externos."><SuccessBlock title="Correo pendiente de verificación" text="Usa el botón para simular una verificación correcta." to="/app/dashboard" action="Simular verificación"/><Link className="mt-4 block text-center text-sm text-primary" to="/login">Volver al inicio</Link></AuthLayout>; }
export function ResetPasswordPage() { const nav=useNavigate(); const schema=z.object({password:z.string().min(8,'Usa al menos 8 caracteres'),confirm:z.string()}).refine(v=>v.password===v.confirm,{path:['confirm'],message:'Las contraseñas no coinciden'}); const {register,handleSubmit,formState:{errors}}=useForm<z.infer<typeof schema>>({resolver:zodResolver(schema)}); return <AuthLayout title="Crea una nueva contraseña" description="La actualización es simulada y solo demuestra el formulario."><form className="grid gap-5" onSubmit={handleSubmit(()=>nav('/login'))}><PasswordField label="Nueva contraseña" error={errors.password?.message} {...register('password')}/><PasswordField label="Confirmar contraseña" error={errors.confirm?.message} {...register('confirm')}/><Button type="submit">Guardar contraseña</Button></form></AuthLayout>; }
function SuccessBlock({title,text,to,action}:{title:string;text:string;to:string;action:string}) { return <div className="text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-success-container text-success"><MaterialIcon name="mark_email_read" size={30}/></span><h3 className="mt-4 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm text-text-secondary">{text}</p><Link to={to}><Button className="mt-6 w-full">{action}</Button></Link></div>; }
