// Application-owned text only. User names, descriptions and category names stay unchanged.
export const applicationEnglish: Record<string, string> = {
  "% del límite utilizado": "% of the limit used",
  "% usado": "% used",
  "% utilizado": "% used",
  "(archivada)": "(archived)",
  "(inactiva)": "(inactive)",
  "(opcional)": "(optional)",
  ". El consumo corresponde al período completo de cada presupuesto. Los límites por categoría de un plan están dentro de su detalle.": ". Spending covers each budget’s full period. A plan’s category limits are shown in its details.",
  ". El historial conserva los movimientos de las cuentas archivadas.": ". Transactions from archived accounts remain in your history.",
  ". La fecha indica el inicio de cada bloque.": ". The date marks the start of each interval.",
  ". No incluye deudas ni otras monedas.": ". Excludes debts and other currencies.",
  ". No incluye ingresos ni transferencias.": ". Excludes income and transfers.",
  ". Puedes elegir otra moneda o": ". You can select another currency or",
  ". Se conserva el registro interno mediante eliminación lógica. No hay restauración desde esta pantalla.": ". The internal record is retained through soft deletion. You cannot restore it from this screen.",
  "5 + otras": "5 + others",
  "Abrir presupuesto": "Open budget",
  "Activa": "Active",
  "Activas": "Active",
  "Activos": "Active",
  "Activos y coincidentes con el período ·": "Active and overlapping this period ·",
  "Actualizado:": "Updated:",
  "Actualizando…": "Updating…",
  "Actualizar progreso": "Refresh progress",
  "Ahorro": "Savings",
  "Ahorro del período": "Period savings",
  "Ahorro proyectado": "Projected savings",
  "Ajusta tus categorías": "Adjust your categories",
  "Ajusta tus límites y visualiza cómo se reparte tu dinero.": "Adjust limits and see how your money is allocated.",
  "Ajustar límite de {0}": "Adjust limit for {0}",
  "Ambos días están incluidos. El progreso se actualiza al registrar, editar o eliminar un gasto. No incluye ingresos ni transferencias.": "Both dates are included. Progress updates when expenses are added, edited or deleted. Excludes income and transfers.",
  "Anterior": "Previous",
  "Anual": "Yearly",
  "Aplicar": "Apply",
  "Aplicar filtros": "Apply filters",
  "Archivada": "Archived",
  "Archivado": "Archived",
  "Archivados": "Archived",
  "Archivar": "Archive",
  "Archivar cuenta": "Archive account",
  "Archivar presupuesto": "Archive budget",
  "Archivar presupuesto mensual": "Archive monthly budget",
  "Así van tus finanzas. Un paso a la vez.": "Your finances at a glance. One step at a time.",
  "Añade tu primera cuenta bancaria, tus ahorros o el efectivo de tu billetera. Tú decides por dónde comenzar.": "Add your first bank account, savings or cash wallet. Choose where to start.",
  "Añadir categoría": "Add category",
  "Año": "Year",
  "Aún no hay presupuestos activos para esta selección.": "No active budgets match this selection yet.",
  "Balance del período ·": "Period balance ·",
  "Balance neto del período": "Net balance for the period",
  "Balance total ·": "Total balance ·",
  "Buscar categorías": "Search categories",
  "Buscar cuenta o institución": "Search account or institution",
  "Buscar cuentas": "Search accounts",
  "Buscar por descripción": "Search by description",
  "Buscar transacción": "Search transactions",
  "Buscar una categoría": "Search for a category",
  "Cambia el período o registra tu primera transacción.": "Change the period or add your first transaction.",
  "Cambiar período": "Change period",
  "Cambios sin guardar": "Unsaved changes",
  "Cargando resumen financiero": "Loading financial overview",
  "Categoría": "Category",
  "Categoría de gasto": "Expense category",
  "Categoría inactiva": "Inactive category",
  "Categoría {0}": "Category {0}",
  "Cerrar aviso": "Dismiss notice",
  "Cerrar ventana": "Close window",
  "Color": "Color",
  "Color de la cuenta": "Account color",
  "Color {0}": "Color {0}",
  "Comparación de ingresos y gastos. Las cifras exactas están en la tabla desplegable.": "Income and expense comparison. Exact figures are in the expandable table.",
  "Comprueba tu conexión y que tu sesión siga activa. Tus datos no se han modificado; no mostramos cifras en cero cuando falla la consulta.": "Check your connection and that you are still signed in. Your data has not changed; we do not show zero amounts when a query fails.",
  "Confirmar archivo": "Confirm archive",
  "Confirmar desactivación": "Confirm deactivation",
  "Confirmar eliminación": "Confirm deletion",
  "Confirmar reactivación": "Confirm reactivation",
  "Conservar": "Keep",
  "Consulta, filtra y administra tus movimientos.": "Browse, filter and manage your transactions.",
  "Consultando…": "Loading…",
  "Consumo de {0}": "Spending for {0}",
  "Consumo real del límite": "Actual spending against limit",
  "Copiar": "Copy",
  "Copiar a otro mes": "Copy to another month",
  "Copiar al nuevo mes": "Copy to new month",
  "Copiar presupuesto": "Copy budget",
  "Copiar {0}": "Copy {0}",
  "Crea tu primer límite o cambia los filtros para consultar otros períodos.": "Create your first limit or change filters to view other periods.",
  "Crea una forma sencilla de organizar tus ingresos o gastos.": "Create a simple way to organize your income or expenses.",
  "Creadas por ti": "Created by you",
  "Crear categoría": "Create category",
  "Crear categoría nueva": "Create new category",
  "Crear cuenta": "Create account",
  "Crear mi presupuesto mensual": "Create my monthly budget",
  "Crear mi primera cuenta": "Create my first account",
  "Crear presupuesto": "Create budget",
  "Crear presupuesto mensual": "Create monthly budget",
  "Cuenta": "Account",
  "Dale sentido a cada ingreso y cada gasto.": "Make sense of every income and expense.",
  "Dale un espacio a tu dinero. No necesitas compartir números de cuenta ni datos de acceso bancario.": "Give your money a place. No account numbers or bank login details required.",
  "Dale un plan a tu dinero": "Give your money a plan",
  "Define un límite mensual, reparte el dinero y consulta cómo van tus gastos. Puedes reutilizar cualquier mes como plantilla.": "Set a monthly limit, allocate your money and track spending. You can reuse any month as a template.",
  "Dejará de aparecer en el historial y se revertirá su efecto en": "It will be removed from your history and its effect will be reversed on",
  "Dejará de estar disponible para nuevos movimientos y presupuestos. Los registros existentes se conservan. Podrás reactivarla cuando quieras.": "It will no longer be available for new transactions and budgets. Existing records remain. You can reactivate it anytime.",
  "Desactivar": "Deactivate",
  "Desactivar categoría": "Deactivate category",
  "Descripción": "Description",
  "Descripción (opcional)": "Description (optional)",
  "Desde": "From",
  "Desglose de categorías": "Category breakdown",
  "Destino": "Destination",
  "Detalle de cuenta": "Account details",
  "Detalle de transacción": "Transaction details",
  "Dinero que gastaste": "Money you spent",
  "Dinero que recibiste": "Money you received",
  "Disponible": "Available",
  "Disponible estimado": "Estimated available",
  "Disponible real": "Actual available",
  "Distribución guardada": "Allocation saved",
  "Distribución por categorías ·": "Breakdown by category ·",
  "Distribución por cuenta": "Breakdown by account",
  "Déficit de {0}: gastaste más de lo que ingresaste.": "Deficit of {0}: you spent more than you earned.",
  "Editar": "Edit",
  "Editar categoría": "Edit category",
  "Editar cuenta": "Edit account",
  "Editar presupuesto": "Edit budget",
  "Editar transacción": "Edit transaction",
  "Editar {0}": "Edit {0}",
  "Ej. 22500": "E.g. 22500",
  "Ej. 30000": "E.g. 30000",
  "Ej. 50000": "E.g. 50000",
  "Ej. Alimentación del mes": "E.g. Monthly groceries",
  "Ej. Banco Popular": "E.g. Banco Popular",
  "Ej. Compra del supermercado": "E.g. Grocery shopping",
  "Ej. Cuenta principal": "E.g. Main account",
  "Ej. Mascotas o Trabajo independiente": "E.g. Pets or Freelance work",
  "Ej. Tarjeta, efectivo, transferencia": "E.g. Card, cash, transfer",
  "El mes muestra los presupuestos que coinciden con él, pero cada progreso abarca su período completo, sin prorratear. El resumen suma los presupuestos filtrados; si incluyes archivados, pueden solaparse. No es tu gasto total. Solo cuentan gastos no eliminados en la misma moneda. Zona horaria:": "The month shows overlapping budgets, but progress covers each full period without prorating. The summary adds filtered budgets; including archived ones may cause overlap. This is not your total spending. Only non-deleted expenses in the same currency count. Time zone:",
  "El presupuesto está creado. Añade tu primera categoría para comenzar a repartirlo.": "Your budget is ready. Add your first category to start allocating it.",
  "El tipo se define al crearla y no cambia después, para conservar la clasificación del historial.": "The type is set when created and cannot change, preserving your history’s classification.",
  "Elige una categoría y cuánto quieres gastar. Te ayudamos a seguir el progreso.": "Choose a category and spending limit. We help you track progress.",
  "Eliminando…": "Deleting…",
  "Eliminar": "Delete",
  "En la misma moneda se registra el mismo importe en ambas cuentas. La transferencia no se cuenta como ingreso ni gasto.": "Transfers in the same currency use the same amount in both accounts. Transfers are not income or expenses.",
  "Escribe el importe real recibido. No se aplica una tasa de cambio automática.": "Enter the actual amount received. No automatic exchange rate is applied.",
  "Escribe el saldo al comenzar, sin separadores de miles. Ejemplo: 2500.50. Para una deuda, usa un saldo negativo.": "Enter the starting balance without thousands separators. Example: 2500.50. Use a negative balance for debt.",
  "Esta categoría viene incluida en PagaTo. Puedes personalizarla para tu cuenta.": "This category comes with PagaTo. You can customize it for your account.",
  "Esta cuenta tiene movimientos. El tipo, la moneda y el saldo inicial no se pueden cambiar para conservar su historial.": "This account has transactions. Its type, currency and opening balance are locked to preserve history.",
  "Estado": "Status",
  "Estado de las cuentas": "Account status",
  "Estas cifras son una proyección, no movimientos reales. El ahorro se calcula como ingreso estimado menos gastos planificados.": "These figures are projections, not real transactions. Savings equal estimated income minus planned expenses.",
  "Este presupuesto está archivado. Puedes consultarlo, copiarlo o reactivarlo.": "This budget is archived. You can view, copy or reactivate it.",
  "Este registro no ejecuta pagos bancarios. Se permiten saldos negativos para reflejar deudas o movimientos pendientes de completar.": "This record does not make bank payments. Negative balances are allowed to reflect debts or pending transactions.",
  "Excedido": "Exceeded",
  "Exceso de asignación:": "Overallocated:",
  "Fecha": "Date",
  "Fecha final": "End date",
  "Fecha inicial": "Start date",
  "Fecha y hora": "Date and time",
  "Filtrar por moneda": "Filter by currency",
  "Filtrar transacciones": "Filter transactions",
  "Filtros del resumen": "Overview filters",
  "Flujo de efectivo": "Cash flow",
  "Gastado realmente": "Actual spending",
  "Gasto": "Expense",
  "Gastos": "Expenses",
  "Gastos activos": "Active expenses",
  "Gastos del período": "Period expenses",
  "Gastos planificados": "Planned expenses",
  "Gastos reales del mes": "Actual monthly expenses",
  "Gastos ·": "Expenses ·",
  "Gestionar categorías": "Manage categories",
  "Guardar distribución": "Save allocation",
  "Guardar transacción": "Save transaction",
  "Hasta": "To",
  "Hay una versión más reciente. Conservamos tu borrador; recarga antes de guardar para evitar sobrescribir cambios.": "A newer version is available. Your draft is preserved; refresh before saving to avoid overwriting changes.",
  "Historial de transacciones": "Transaction history",
  "Historial de transacciones; abre una descripción para ver el detalle": "Transaction history; open a description for details",
  "Hola,": "Hello,",
  "Icono": "Icon",
  "Importes exactos en": "Exact amounts in",
  "Inactiva": "Inactive",
  "Inactivas": "Inactive",
  "Incluye todos los gastos de": "Includes all expenses in",
  "Ingreso": "Income",
  "Ingreso mensual estimado": "Estimated monthly income",
  "Ingreso mensual estimado (opcional)": "Estimated monthly income (optional)",
  "Ingresos": "Income",
  "Ingresos activos": "Active income",
  "Ingresos del período": "Period income",
  "Ingresos menos gastos. El ahorro es el excedente positivo de este período, no el saldo de una cuenta de ahorro.": "Income minus expenses. Savings are the positive surplus for this period, not a savings account balance.",
  "Ingresos ·": "Income ·",
  "Inicio del bloque": "Interval start",
  "Institución": "Institution",
  "Institución (opcional)": "Institution (optional)",
  "Ir a mis cuentas": "Go to my accounts",
  "La cuenta dejará de incluirse en los totales activos. Su historial se conserva y podrás reactivarla cuando quieras.": "The account will be excluded from active totals. Its history is preserved and you can reactivate it anytime.",
  "La cuenta volverá a mostrarse entre tus cuentas activas y a incluirse en sus totales.": "The account will be shown among your active accounts and included in their totals again.",
  "La distribución supera el límite mensual. Ajusta los importes antes de guardar.": "The allocation exceeds the monthly limit. Adjust the amounts before saving.",
  "Las predeterminadas vienen incluidas en PagaTo y puedes personalizarlas. Desactivar una categoría no borra sus movimientos ni sus presupuestos. Solo tú ves tus categorías.": "Default categories come with PagaTo and can be customized. Deactivating a category does not delete its transactions or budgets. Only you can see your categories.",
  "Las tarjetas muestran la distribución guardada. Quitar una categoría del plan no elimina sus movimientos. Zona horaria:": "Cards show the saved allocation. Removing a category from the plan does not delete its transactions. Time zone:",
  "Las transferencias no se suman como ingresos ni gastos.": "Transfers are not counted as income or expenses.",
  "Limpiar": "Clear",
  "Limpiar filtros": "Clear filters",
  "Los cambios recalculan los saldos de las cuentas involucradas.": "Changes recalculate the balances of the affected accounts.",
  "Los ingresos y gastos aparecerán aquí al registrarlos.": "Income and expenses will appear here when you add them.",
  "Los movimientos que registres aparecerán aquí. Las transferencias no forman parte de este gráfico.": "Your transactions will appear here. Transfers are not included in this chart.",
  "Límite categoría": "Category limit",
  "Límite categoría {0}": "Category {0} limit",
  "Límite de crédito": "Credit limit",
  "Límite de crédito (opcional)": "Credit limit (optional)",
  "Límite de gasto": "Spending limit",
  "Límite mensual": "Monthly limit",
  "Límite superado en": "Limit exceeded by",
  "Límites individuales": "Individual limits",
  "Mensual": "Monthly",
  "Mes": "Month",
  "Mes del presupuesto": "Budget month",
  "Moneda": "Currency",
  "Monto": "Amount",
  "Monto enviado": "Amount sent",
  "Monto recibido (": "Amount received (",
  "Mostrando": "Showing",
  "Movimiento entre cuentas propias: no se suma a tus ingresos o gastos.": "Transfer between your own accounts: not counted as income or expenses.",
  "Movimientos recientes": "Recent transactions",
  "Mueve los controles o escribe un importe exacto. La suma de los límites no puede superar el límite mensual.": "Move the sliders or enter an exact amount. Category limits cannot add up to more than the monthly limit.",
  "Máximo de la escala:": "Scale maximum:",
  "Método de pago": "Payment method",
  "Necesitas una categoría de gasto activa para crear un presupuesto.": "You need an active expense category to create a budget.",
  "No cambia con el período. Las monedas se consultan por separado.": "Unaffected by the period. View each currency separately.",
  "No encontramos cuentas": "No accounts found",
  "No hay categorías para mostrar": "No categories to display",
  "No hay ingresos ni gastos en este período.": "No income or expenses in this period.",
  "No hay movimientos en esta selección.": "No transactions match this selection.",
  "No hay movimientos para mostrar": "No transactions to display",
  "No hay presupuestos mensuales en esta selección. Crea uno o elige Ver todos para copiar un mes anterior.": "No monthly budgets match this selection. Create one or choose View all to copy a previous month.",
  "No indicado": "Not specified",
  "No pudimos cargar tu resumen": "We could not load your overview",
  "No puede existir otro presupuesto activo para el mismo mes y moneda.": "Only one active budget is allowed per month and currency.",
  "No se suma a tu saldo: es el límite autorizado de la tarjeta.": "Not added to your balance: this is the card’s authorized limit.",
  "No tienes cuentas activas en": "You have no active accounts in",
  "Nombre": "Name",
  "Nombre de la categoría": "Category name",
  "Nombre de la cuenta": "Account name",
  "Nombre del presupuesto": "Budget name",
  "Notas": "Notes",
  "Nueva categoría": "New category",
  "Nueva cuenta": "New account",
  "Nueva transacción": "New transaction",
  "Nuevo presupuesto": "New budget",
  "Nuevo presupuesto mensual": "New monthly budget",
  "Ocultar filtros": "Hide filters",
  "Opcional": "Optional",
  "Organiza tu dinero por cuenta y propósito.": "Organize your money by account and purpose.",
  "Origen": "Source",
  "Perfil de {0}": "Profile of {0}",
  "Personalizada": "Custom",
  "Personalizadas": "Custom",
  "Personalizado": "Custom",
  "Período": "Period",
  "Plan mensual ·": "Monthly plan ·",
  "Planifica tu mes": "Plan your month",
  "Planificar un presupuesto": "Plan a budget",
  "Ponle un límite a tus gastos. Incluiremos los movimientos de la categoría, moneda y período que elijas.": "Set a spending limit. We include expenses matching your category, currency and period.",
  "Por bloques de 7 días desde el inicio": "In 7-day intervals from the start",
  "Por categoría": "By category",
  "Por día": "By day",
  "Por mes": "By month",
  "Predeterminada": "Default",
  "Predeterminadas": "Default",
  "Prepara tu próximo mes": "Prepare your next month",
  "Preparando tu resumen financiero…": "Preparing your financial overview…",
  "Preparando…": "Preparing…",
  "Presupuesto": "Budget",
  "Presupuestos mensuales": "Monthly budgets",
  "Presupuestos por categoría, independientes de un plan mensual.": "Category budgets, independent of a monthly plan.",
  "Primero define tu mes y límite total. Después podrás repartirlo entre las categorías que elijas.": "Choose your month and total limit first. Then allocate it to your categories.",
  "Primero necesitas una cuenta activa.": "You need an active account first.",
  "Primero tu mes, después tus categorías": "Your month first, your categories next",
  "Progreso de {0}": "Progress for {0}",
  "Progreso real por categoría": "Actual progress by category",
  "Prueba otro nombre, moneda o estado. Las cuentas archivadas siguen guardadas aquí.": "Try another name, currency or status. Archived accounts are still saved here.",
  "Prueba otros filtros o crea una categoría para": "Try other filters or create a category for",
  "Páginas de presupuestos": "Budget pages",
  "Páginas del historial": "History pages",
  "Quitar categoría {0}": "Remove category {0}",
  "Reactiva esta categoría o quítala de la distribución antes de guardar.": "Reactivate this category or remove it from the allocation before saving.",
  "Reactivar": "Reactivate",
  "Reactivar categoría": "Reactivate category",
  "Reactivar cuenta": "Reactivate account",
  "Reactivar presupuesto": "Reactivate budget",
  "Reactivar presupuesto mensual": "Reactivate monthly budget",
  "Registra lo que entra, lo que sale y lo que mueves entre tus cuentas.": "Track money coming in, going out and moving between your accounts.",
  "Registra tu primer ingreso, gasto o transferencia, o ajusta los filtros para encontrar movimientos anteriores.": "Add your first income, expense or transfer, or adjust filters to find earlier transactions.",
  "Registrar movimiento": "Add transaction",
  "Reintentando…": "Retrying…",
  "Repartido": "Allocated",
  "Resumen de categorías": "Category overview",
  "Resumen de cuentas activas": "Active account overview",
  "Resumen de presupuestos": "Budget overview",
  "Resumen de todos los resultados filtrados, no solo de esta página. No incluye transferencias ni mezcla monedas. No es el saldo de tus cuentas.": "Summary of all filtered results, not just this page. Excludes transfers and keeps currencies separate. This is not your account balance.",
  "Resumen del historial filtrado": "Filtered history overview",
  "Resumen del período": "Period overview",
  "Saldo actual de tus cuentas activas.": "Current balance of your active accounts.",
  "Saldo actual ·": "Current balance ·",
  "Saldo actual:": "Current balance:",
  "Saldo de cuentas activas": "Active account balance",
  "Saldo inicial": "Opening balance",
  "Saldo inicial (": "Opening balance (",
  "Saldos positivos en": "Positive balances in",
  "Selecciona otro período o registra tu primer gasto.": "Select another period or add your first expense.",
  "Selecciona un movimiento para ver su detalle. El historial completo incluye todas las monedas.": "Select a transaction to see details. Full history includes all currencies.",
  "Selecciona una categoría": "Select a category",
  "Selecciona una categoría activa o reactiva la anterior desde Ajustes.": "Select an active category or reactivate the previous one in Settings.",
  "Seleccionar categoría": "Select category",
  "Seleccionar cuenta": "Select account",
  "Siguiente": "Next",
  "Sin asignar": "Unallocated",
  "Sin asignar:": "Unallocated:",
  "Sin descripción": "No description",
  "Sin institución": "No institution",
  "Sin notas": "No notes",
  "Sin presupuestos para esta selección": "No budgets match this selection",
  "Sin separadores de miles. No convertimos gastos entre monedas.": "No thousands separators. Expenses are not converted between currencies.",
  "Sin separadores de miles. Se admiten hasta 4 decimales.": "No thousands separators. Up to 4 decimal places allowed.",
  "Solo se usa para proyectar el ahorro. No registra un ingreso ni cambia tus cuentas.": "Used only to project savings. Does not record income or change your accounts.",
  "Tasa de ahorro": "Savings rate",
  "Tasa de ahorro: {0}": "Savings rate: {0}",
  "Tasa no disponible: no hay ingresos": "Rate unavailable: no income",
  "Tipo": "Type",
  "Tipo de categoría": "Category type",
  "Tipo de categorías": "Category types",
  "Tipo de cuenta": "Account type",
  "Tipo de movimiento": "Transaction type",
  "Todas": "All",
  "Todas las categorías": "All categories",
  "Todas las cuentas": "All accounts",
  "Todavía no hay gastos que distribuir.": "No expenses to break down yet.",
  "Todos": "All",
  "Todos los estados": "All statuses",
  "Todos los orígenes": "All sources",
  "Todos los tipos": "All types",
  "Transacciones": "Transactions",
  "Transferencia": "Transfer",
  "Transferir": "Transfer",
  "Tu categoría": "Your category",
  "Tu dinero, bien organizado": "Your money, well organized",
  "Tu historial, más claro.": "Your history, made clear.",
  "Tus categorías": "Your categories",
  "Tus cuentas": "Your accounts",
  "Tus cuentas se guardan en PagaTo. No realizamos conexiones bancarias ni movimientos de dinero.": "Your accounts are saved in PagaTo. We do not connect to banks or move money.",
  "Tus límites por categoría": "Your category limits",
  "Tus presupuestos": "Your budgets",
  "Tus presupuestos anteriores siguen disponibles, sin cambios. También puedes crear límites por categoría sin agruparlos en un mes.": "Your previous budgets remain unchanged. You can also create category limits without grouping them into a month.",
  "Ubicación": "Location",
  "Un plan para tu mes. Cada categoría, bajo tu control.": "A plan for your month. Every category under your control.",
  "Un presupuesto activo por mes y moneda. Los gastos que ya existan en el mes de destino se reflejarán automáticamente.": "One active budget per month and currency. Existing expenses in the target month will be reflected automatically.",
  "Usa cuentas y categorías activas.": "Use active accounts and categories.",
  "Usa «{0}» como plantilla. Copiaremos el límite, el ingreso estimado y las categorías con sus importes, no sus gastos.": "Use “{0}” as a template. We copy the limit, estimated income and category allocations, not expenses.",
  "Ver cifras del gráfico": "View chart figures",
  "Ver detalle de {0}": "View details for {0}",
  "Ver detalle: {0}": "View details: {0}",
  "Ver historial": "View history",
  "Ver límites individuales": "View individual limits",
  "Ver mis cuentas": "View my accounts",
  "Ver todos": "View all",
  "Vista previa": "Preview",
  "Volverá a estar disponible para clasificar nuevos movimientos. No se creará otra categoría ni se modificará tu historial.": "It will be available for new transactions again. No duplicate category is created and your history stays unchanged.",
  "Zona horaria del perfil:": "Profile time zone:",
  "a las": "at",
  "ambas cuentas": "both accounts",
  "bienvenido": "welcome",
  "categoría mostrada": "category shown",
  "categorías": "categories",
  "categorías asignadas": "allocated categories",
  "categorías mostradas": "categories shown",
  "crear una cuenta": "create an account",
  "cuenta activa": "active account",
  "cuenta mostrada": "account shown",
  "cuentas activas": "active accounts",
  "cuentas mostradas": "accounts shown",
  "de": "of",
  "de límite": "limit",
  "del mes, aunque no tengan un límite asignado. Fuera de las categorías asignadas:": "for the month, even without an assigned limit. Outside allocated categories:",
  "del período en": "for the period in",
  "el saldo de la cuenta": "the account balance",
  "gasto": "expense",
  "gastos": "expenses",
  "límite": "limit",
  "límites": "limits",
  "movimiento": "transaction",
  "movimientos": "transactions",
  "presupuesto": "budget",
  "presupuestos": "budgets",
  "presupuestos mensuales · Página": "monthly budgets · Page",
  "tus gastos": "your expenses",
  "tus ingresos": "your income",
  "{0} de exceso": "{0} over limit",
  "{0} disponibles": "{0} available",
  "{0}% utilizado": "{0}% used",
  "{0}% utilizado. {1}": "{0}% used. {1}",
  "{0}% utilizado. {1}.": "{0}% used. {1}.",
  "{0}: ingresos {1}, gastos {2}": "{0}: income {1}, expenses {2}",
  "«{0}» pasará a Archivados. Se conservarán su distribución y sus movimientos.": "“{0}” will move to Archived. Its allocation and transactions will be preserved.",
  "· Página": "· Page",
  "· Totales por moneda, sin conversión.": "· Totals by currency, without conversion.",
  "¿Archivar «{0}»? Podrás consultarlo en Archivados. Tus gastos y saldos no se modificarán.": "Archive “{0}”? You can view it in Archived. Your expenses and balances will not change.",
  "¿Eliminar esta transacción?": "Delete this transaction?",
  "¿En qué estás gastando?": "Where is your money going?",
  "¿Para qué usarás esta cuenta?": "What will you use this account for?",
  "¿Prefieres un límite individual?": "Prefer an individual limit?",
  "¿Reactivar «{0}»? La categoría debe estar activa y no puede solaparse con otro presupuesto de la misma categoría y moneda.": "Reactivate “{0}”? The category must be active and cannot overlap another budget for the same category and currency.",
  "Últimos": "Latest"
};
