export const feedbackEnglish: Record<string, string> = {
  "No pudimos guardar la cuenta. Revisa tu conexión e inténtalo de nuevo.": "We could not save the account. Check your connection and try again.",
  "La cuenta cambió, tiene movimientos o ya no está disponible. Cierra este formulario y actualiza la página antes de reintentar.": "The account changed, has transactions or is no longer available. Close this form and refresh before trying again.",
  "Cambios guardados.": "Changes saved.",
  "Cuenta creada correctamente.": "Account created.",
  "Cuenta reactivada.": "Account reactivated.",
  "Cuenta archivada. Su historial se conserva.": "Account archived. Its history is preserved.",
  "La categoría cambió o ya no está disponible. Cierra este formulario y actualiza la página. El tipo no puede cambiarse.": "The category changed or is no longer available. Close this form and refresh. Its type cannot be changed.",
  "No pudimos guardar los cambios. Comprueba tu conexión e inténtalo de nuevo.": "We could not save changes. Check your connection and try again.",
  "Ya tienes una categoría de ese tipo con ese nombre, incluso entre las inactivas.": "You already have a category of this type with that name, including inactive categories.",
  "Usa otro nombre o reactiva la categoría existente.": "Use another name or reactivate the existing category.",
  "Categoría actualizada.": "Category updated.",
  "Categoría creada correctamente.": "Category created.",
  "Categoría reactivada.": "Category reactivated.",
  "Categoría desactivada. Su historial se conserva.": "Category deactivated. Its history is preserved.",
  "No se guardó el movimiento. Puede haber cambiado; verifica que las cuentas y la categoría estén activas y sean compatibles. En la misma moneda, el importe enviado y recibido debe coincidir. Actualiza la página antes de reintentar.": "The transaction was not saved. It may have changed; check that accounts and category are active and compatible. For the same currency, sent and received amounts must match. Refresh before retrying.",
  "No pudimos confirmar el guardado. Revisa la conexión y reintenta sin cerrar el formulario; no duplicaremos la misma solicitud.": "We could not confirm the save. Check your connection and retry without closing the form; the same request will not be duplicated.",
  "El movimiento excedería el saldo máximo admitido por una cuenta. Reduce el importe.": "This transaction would exceed the maximum account balance. Reduce the amount.",
  "Transacción actualizada. Los saldos están al día.": "Transaction updated. Balances are up to date.",
  "Transacción registrada. Los saldos están al día.": "Transaction recorded. Balances are up to date.",
  "El movimiento cambió o ya fue eliminado. Actualiza la página para comprobarlo.": "The transaction changed or was already deleted. Refresh the page to check.",
  "No pudimos confirmar la eliminación. Actualiza el historial para comprobar el estado antes de reintentar.": "We could not confirm deletion. Refresh history to check its status before retrying.",
  "Transacción eliminada del historial. Su efecto en los saldos se ha revertido.": "Transaction removed from history. Its effect on balances has been reversed.",
  "No se guardó el cambio. Revisa que la categoría esté activa y no haya otro presupuesto activo para esa categoría y moneda con fechas que se solapen. Si el presupuesto cambió, cierra el formulario y actualiza la página.": "Changes were not saved. Check that the category is active and no active budget overlaps for the same category and currency. If the budget changed, close the form and refresh.",
  "No pudimos confirmar el guardado. Revisa tu conexión y reintenta sin cerrar el formulario; la misma solicitud no se duplicará.": "We could not confirm the save. Check your connection and retry without closing the form; the same request will not be duplicated.",
  "Presupuesto actualizado. El progreso se recalculó con tus gastos.": "Budget updated. Progress was recalculated using your expenses.",
  "Presupuesto creado. Ya incluye los gastos de ese período.": "Budget created. It already includes expenses for that period.",
  "Presupuesto archivado. Tus gastos no se modificaron.": "Budget archived. Your expenses were not changed.",
  "Presupuesto reactivado.": "Budget reactivated.",
  "No se guardó. El presupuesto pudo cambiar o ya existe uno activo para ese mes y moneda. Comprueba las categorías activas y recarga antes de reintentar.": "Not saved. The budget may have changed or an active one already exists for that month and currency. Check active categories and refresh before retrying.",
  "No pudimos confirmar el guardado. Revisa tu conexión y reintenta sin cerrar el formulario.": "We could not confirm the save. Check your connection and retry without closing the form.",
  "Presupuesto copiado. No se copiaron movimientos.": "Budget copied. No transactions were copied.",
  "Presupuesto guardado.": "Budget saved.",
  "Revisa los datos y los límites de las categorías.": "Check the data and category limits.",
  "Revisa el nombre y el mes de destino.": "Check the name and target month.",
  "Hay categorías inactivas en el presupuesto original. Reactívalas o retíralas antes de copiar; no omitiremos categorías sin avisarte.": "The original budget has inactive categories. Reactivate or remove them before copying; no categories will be silently skipped.",
  "Presupuesto archivado. Los movimientos no cambian.": "Budget archived. Transactions stay unchanged.",
  "No pudimos abrir el formulario. Revisa la conexión y que tu sesión siga activa.": "We could not open the form. Check your connection and that you are still signed in.",
  "No pudimos abrir el formulario. Reintenta o vuelve a iniciar sesión.": "We could not open the form. Try again or sign in again.",
  "Revisa las fechas: el rango debe estar ordenado y no superar 366 días.": "Check the dates: the range must be in order and no longer than 366 days.",
  "Usa un número sin separadores de miles y con hasta 4 decimales.": "Use a number without thousands separators and with up to 4 decimal places.",
  "El identificador no es válido.": "Invalid identifier.",
  "Escribe un nombre para la cuenta.": "Enter an account name.",
  "El límite no puede ser negativo.": "The limit cannot be negative.",
  "Selecciona un mes válido.": "Select a valid month.",
  "Usa un importe válido con hasta cuatro decimales.": "Use a valid amount with up to four decimal places.",
  "El importe debe ser mayor que cero.": "The amount must be greater than zero.",
  "Escribe un nombre.": "Enter a name.",
  "Selecciona una categoría.": "Select a category.",
  "Actualiza el presupuesto antes de guardar.": "Refresh the budget before saving.",
  "No repitas una categoría.": "Do not repeat a category.",
  "La suma de categorías supera el límite mensual. Reduce los importes o aumenta el límite.": "Category allocations exceed the monthly limit. Reduce the amounts or increase the limit.",
  "Indica una fecha válida.": "Enter a valid date.",
  "Selecciona una categoría de gasto.": "Select an expense category.",
  "Escribe un monto mayor que cero, sin separadores de miles y con hasta 4 decimales.": "Enter an amount greater than zero, without thousands separators and with up to 4 decimal places.",
  "La fecha final no puede ser anterior a la inicial.": "The end date cannot be before the start date.",
  "Indica una fecha y hora válidas.": "Enter a valid date and time.",
  "Selecciona la cuenta de origen.": "Select the source account.",
  "Selecciona una cuenta con moneda válida.": "Select an account with a valid currency.",
  "Selecciona la cuenta de destino.": "Select the destination account.",
  "Elige una cuenta diferente a la de origen.": "Choose an account different from the source.",
  "Indica el importe recibido.": "Enter the amount received.",
  "Elige un icono de la lista.": "Choose an icon from the list.",
  "Elige un color válido.": "Choose a valid color.",
  "Escribe un nombre para la categoría.": "Enter a category name.",
  "Estado actualizado.": "Status updated.",
  "Categoría guardada.": "Category saved.",
  "Transacción registrada.": "Transaction recorded.",
  "Transacción eliminada.": "Transaction deleted.",
  "Naranja": "Orange",
  "Coral": "Coral",
  "Gris": "Gray",
  "Tienes cambios sin guardar. ¿Salir del presupuesto?": "You have unsaved changes. Leave the budget?",
  "Si no aparece, revisa los filtros de mes y estado.": "If it is not visible, check the month and status filters."
};
