import { useState } from 'react';
import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { Button, Drawer, IconButton, MaterialIcon, PrivacyAmountToggle, SearchField, ThemeToggle, Tooltip } from '../ui';
import { cn } from '../../lib/utils';
import { useAuth } from '../../app/auth';

const nav = [
  ['/app/dashboard','dashboard','Dashboard'], ['/app/transactions','receipt_long','Transacciones'], ['/app/accounts','account_balance','Cuentas'],
  ['/app/budgets','account_balance_wallet','Presupuestos'], ['/app/reports','bar_chart','Reportes'], ['/app/settings','settings','Configuración'],
] as const;

function NavContent({ onNavigate, onLogout }: {onNavigate?:()=>void;onLogout:()=>void}) { return <div className="flex h-full flex-col p-4"><NavLink to="/app/dashboard" className="flex min-h-12 items-center gap-3 px-2 text-xl font-semibold text-primary" onClick={onNavigate}><span className="grid size-9 place-items-center rounded-xl bg-primary text-on-primary">P</span><span className="laptop:hidden desktop:inline">PagaTo’</span></NavLink><NavLink to="/app/transactions/new" onClick={onNavigate} className="mt-6"><Button icon="add" className="w-full laptop:px-0 desktop:px-4"><span className="laptop:hidden desktop:inline">Crear movimiento</span></Button></NavLink><nav aria-label="Navegación principal" className="mt-5 grid gap-1">{nav.map(([to,icon,label])=><Tooltip label={label} key={to}><NavLink to={to} onClick={onNavigate} className={({isActive})=>cn('flex min-h-12 items-center gap-3 rounded-full px-4 text-sm font-medium text-text-secondary hover:bg-surface-container',isActive&&'bg-primary-container text-primary')}><MaterialIcon name={icon}/><span className="laptop:hidden desktop:inline">{label}</span></NavLink></Tooltip>)}</nav><div className="mt-auto border-t border-border pt-4"><button onClick={onLogout} className="flex min-h-11 w-full items-center gap-3 rounded-full px-4 text-sm text-text-secondary hover:bg-surface-container"><MaterialIcon name="logout"/><span className="laptop:hidden desktop:inline">Cerrar sesión</span></button></div></div>; }

export function AppShell() { const [drawer,setDrawer]=useState(false); const auth=useAuth(); const nav=useNavigate(); const logout=async()=>{await auth.logout();nav('/login');}; const initials=(auth.user?.displayName||'PagaTo').split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase(); return <div className="desktop-web min-h-screen bg-bg"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 border-r border-border bg-surface laptop:block laptop:w-20 desktop:w-64"><NavContent onLogout={logout}/></aside><Drawer open={drawer} onClose={()=>setDrawer(false)}><NavContent onLogout={logout} onNavigate={()=>setDrawer(false)}/></Drawer><header className="fixed left-0 right-0 top-0 z-20 flex h-16 items-center gap-3 border-b border-border bg-surface/95 px-5 backdrop-blur laptop:left-20 desktop:left-64"><IconButton label="Abrir navegación" icon="menu" className="laptop:hidden" onClick={()=>setDrawer(true)}/><div className="w-full max-w-md tablet-hide"><SearchField/></div><div className="ml-auto flex items-center gap-1"><PrivacyAmountToggle/><IconButton label="Notificaciones" icon="notifications"/><div className="hidden tablet:block"><ThemeToggle/></div><button className="ml-1 grid size-10 place-items-center rounded-full bg-primary-container font-semibold text-primary" aria-label={`Menú de ${auth.user?.displayName||'usuario'}`}>{initials}</button></div></header><main className="min-h-screen pt-16 laptop:pl-20 desktop:pl-64"><div className="mx-auto max-w-[1440px] p-6 laptop:p-8"><Outlet/></div></main></div>; }
export function PageHeader({title,description,action}: {title:string;description:string;action?:React.ReactNode}) { return <header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-[28px] font-medium leading-9">{title}</h1><p className="mt-1 text-sm text-text-secondary">{description}</p></div>{action}</header>; }
